### PR TITLE
Fix whitespace pre support, remove mptt

### PR DESCRIPTION
**Pull request by ferringb**
mptt is obvious, but for whitespace, I'll refer to my commit message.  Note, you may wish to just change the snippet-rendered class to have {whitespace:pre} anyways- it seems like a default has less of a potential to surprise users.

If someone posts python code, but labels it as text- say something like thus:
```
if blah:
  print "me!"
```

dpaste was rendering that as
```
if blah
print "me!"
```

We may wish to make the snippet-rendered class have {whitespace: pre} styling;
regardless if dpaste chooses to do so, this change is necessary so any end
consumers can set the styling themselves; to support that, any extra indentation
the template adds must be suppressed.

### CODE REVIEW

**Comment by bartTC** [comment]
> If someone posts python code, but labels it as text- say something like thus:

No, this is correc behaviort. "Text" is literal body text. It's not code. Choose "Code" if you want to display code.

**Comment by ferringb** [comment]
> No, this is correct behavior. "Text" is literal body text. It's not code. Choose "Code" if you want to display code.

I'd agree, except in my case my users haven't paid attention to this (the previous implementation- where I got 60k snippets from- had no real concept of 'type'), and we have some tooling that is heavily used that has the same problem.  Longer term, I think a better fix is to introduce the notion of 'raw'- which is literally just raw unformated (but indentation preserving) text.

In the meantime, could you please take a look at my change again?  Note that I'm explicitly *not* changing text rendering so indentation is preserved- I'm just changing the template slightly so that I can fix this on my deploy via css, rather than having to copy/paste the entire template and fix the extra whitespace.  What I'm proposing doesn't cause any issues for your usage, but allows me to fix my scenario cleanly.

Regardless of that discussion, you probably want the mptt removal I did for requirements.txt.

Thanks-

**Comment by bartTC** [comment]
> I think a better fix is to introduce the notion of 'raw'- which is literally just raw unformated (but indentation preserving) text.

This exists. Choose "Code".

**Comment by ferringb** [comment]
Shit, sorry about that- I missed that that even existed.  That makes sense, thanks.

**Pull request closed without merging**
